farcaster_priv_key = ""
optimism_l2_rpc_url = ""
db_path = "sqlite:./farcaster.db"
db_migrations_path = "./lib/storage/migrations"
id_registry_address = "0x00000000fcaf86937e41ba038b4fa40baa4b780a"
id_registry_abi_path = "./lib/eth/abis/IdRegistry.json"
key_registry_address = "0x00000000fC9e66f1c6d86D750B4af47fF0Cc343d"
key_registry_abi_path = "./lib/eth/abis/KeyRegistry.json"
storage_registry_address = "0x00000000fcce7f938e7ae6d3c335bd6a1a7c593d"
storage_registry_abi_path = "./lib/eth/abis/StorageRegistry.json"
